#!/bin/python3.7
import pyautogui as pg
import time as tm
print("[*] El programa iniciara en 5 segundos. Asegurese de que el gestor de aplicaciones al inicio esté en primer plano (mate-session-properties)")
tm.sleep(5)
pg.press('tab')
pg.press('tab')
pg.press('enter')
pg.write('0v53rber')
pg.press('tab')
pg.write('observer.sh')
pg.press('tab')
pg.press('tab')
pg.press('tab')
pg.press('tab')
pg.press('enter')
pg.press('enter')
pg.write("ch1s3c")
pg.press('tab')
pg.write('chisec.sh')
pg.press('tab')
pg.press('tab')
pg.press('tab')
pg.press('tab')
pg.press('enter')
pg.press('enter')
pg.write("f1ng3r5talk3r")
pg.press('tab')
pg.write('fingerstalker.sh')
pg.press('tab')
pg.press('tab')
pg.press('tab')
pg.press('tab')
pg.press('enter')
pg.hotkey('alt','f4')